### ISSUE TITLE
Excuse me, I want to know what you are based on reference to achieve this Nilsimsa.Could you share with me?

### ISSUE THREAD

**Issue by StarrYMSkY** [weblyzard/nilsimsa#3]

**Comment by AlbertWeichselbraun** [comment]
to the best of my knowledge, the c implementation referenced in README.md has been the first use/publication of this method.

there is also an article discussing nilsimsa in greater detail which has been published afterwards:

  *Damiani, E., De Capitani di Vimercati, S., Paraboschi, S., & Samarati, P. (2004). An Open Digest-based Technique for Spam Detection. In Proceedings of the 2004 International Workshop on Security in Parallel and Distributed Systems, 15–17.*
